"""Iter 84c — Daily 07:00 EAT health summary.

Reads the last 24 hours of `audit_log` rows and emails a rollup to the
SMTP-configured admins. Unlike the per-audit alert, this one fires
EVERY DAY at 07:00 EAT regardless of status — gives executives a
morning "all-clear" instead of relying on silence-as-good-news.

Format:
    Subject: [Daily] Vivo BI — Health Report YYYY-MM-DD
    Body:
        12 audits run in last 24h
        ✓ 10 HEALTHY · ⚠ 1 WARNING (auto-fixed) · ✗ 1 CRITICAL
        Top alert: Fan-out tripwire fired 7× at 16:30 → resolved

Idempotent within the calendar day: a marker row is written to
`audit_log` with `kind=daily_summary` and the day's date; if a marker
already exists for today, we skip. Safe to invoke multiple times.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone, timedelta
from typing import Any, Dict, List

from email_alert import send_alert, email_configured

logger = logging.getLogger("server.audit_daily_summary")


def _format_summary_body(rows: List[Dict[str, Any]]) -> str:
    """Build the plain-text body for the daily rollup."""
    now_eat = datetime.now(timezone.utc) + timedelta(hours=3)
    if not rows:
        return (
            f"Vivo BI — Daily Health Report\n"
            f"Date:  {now_eat.strftime('%Y-%m-%d')}\n\n"
            f"No audits ran in the last 24 hours. Check that the\n"
            f"external cron service (cron-job.org → /api/run-audit) is\n"
            f"still active. The 2-hour cadence should produce ~12 rows.\n"
        )

    by_status = {"HEALTHY": 0, "WARNING": 0, "CRITICAL": 0, "UNKNOWN": 0}
    total_issues = total_fixed = total_escalated = 0
    for r in rows:
        s = r.get("status") or "UNKNOWN"
        by_status[s] = by_status.get(s, 0) + 1
        total_issues += int(r.get("issues_found") or 0)
        total_fixed += int(r.get("issues_auto_fixed") or 0)
        total_escalated += int(r.get("issues_escalated") or 0)

    # Top alerts: collect the unique fix_details lines from non-HEALTHY runs.
    top_alerts: List[str] = []
    for r in sorted(rows, key=lambda x: x.get("timestamp", ""), reverse=True):
        if r.get("status") == "HEALTHY":
            continue
        eat_ts = r.get("timestamp", "?")[:16].replace("T", " ")
        for f in (r.get("fix_details") or [])[:3]:
            outcome = "✓ resolved" if f.get("resolved") else "✗ escalated"
            top_alerts.append(f"  • [{eat_ts}] {f.get('issue', '?')} — {outcome}")
        if len(top_alerts) >= 8:
            break
    top = "\n".join(top_alerts) if top_alerts else "  (no issues — everything green)"

    summary_line = (
        f"✓ {by_status['HEALTHY']} HEALTHY · "
        f"⚠ {by_status['WARNING']} WARNING (auto-fixed) · "
        f"✗ {by_status['CRITICAL']} CRITICAL"
    )

    return (
        f"Vivo BI — Daily Health Report\n"
        f"Date: {now_eat.strftime('%Y-%m-%d')} ({now_eat.strftime('%A')})\n\n"
        f"Last 24 hours: {len(rows)} audit runs\n"
        f"{summary_line}\n\n"
        f"Aggregate issue counts:\n"
        f"  • Found       : {total_issues}\n"
        f"  • Auto-fixed  : {total_fixed}\n"
        f"  • Escalated   : {total_escalated}\n\n"
        f"Top alerts (last 24h):\n"
        f"{top}\n\n"
        f"--\n"
        f"Auto-generated by the standing 2-hour audit job. Critical alerts\n"
        f"continue to fire in real time; this is the daily rollup.\n"
    )


async def send_daily_summary_if_due(db) -> Dict[str, Any]:
    """Idempotent — sends at most ONE daily summary per calendar day.

    Returns {sent, reason, ...details}.

    Mongo marker: `audit_log.{kind=daily_summary_sent, date=YYYY-MM-DD}`.
    """
    now_eat = datetime.now(timezone.utc) + timedelta(hours=3)
    today_eat = now_eat.date().isoformat()

    # Idempotency: skip if we've already sent today.
    existing = await db.audit_log.find_one({
        "kind": "daily_summary_sent",
        "date": today_eat,
    })
    if existing:
        return {"sent": False, "reason": "already_sent_today", "date": today_eat}

    if not email_configured():
        return {"sent": False, "reason": "smtp_not_configured", "date": today_eat}

    # Pull last 24h of audit_log rows (full audits only — exclude the
    # snapshot_sweep and daily_summary_sent marker rows).
    cutoff = datetime.now(timezone.utc) - timedelta(hours=24)
    rows: List[Dict[str, Any]] = []
    try:
        cur = db.audit_log.find(
            {
                "timestamp": {"$exists": True},
                "kind": {"$exists": False},
            },
            {"_id": 0},
        ).sort("timestamp", -1).limit(50)
        async for r in cur:
            ts = r.get("timestamp")
            if isinstance(ts, str):
                try:
                    parsed = datetime.fromisoformat(ts.replace("Z", "+00:00"))
                    if parsed >= cutoff:
                        rows.append(r)
                except Exception:
                    rows.append(r)
            else:
                rows.append(r)
    except Exception as e:
        logger.warning("[daily-summary] audit_log read failed: %s", e)

    subject = f"[Daily] Vivo BI — Health Report {today_eat}"
    body = _format_summary_body(rows)
    send_res = send_alert(subject, body)

    # Mark sent so we don't fire again today even on multiple scheduler ticks.
    try:
        await db.audit_log.insert_one({
            "kind": "daily_summary_sent",
            "date": today_eat,
            "ts": datetime.now(timezone.utc),
            "rows_summarized": len(rows),
            "send_result": send_res,
        })
    except Exception as e:
        logger.warning("[daily-summary] marker insert failed: %s", e)

    return {"sent": bool(send_res.get("ok")), "date": today_eat, "rows": len(rows), **send_res}
